# Generated by Django 4.1.7 on 2023-04-01 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_staus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='staus',
            new_name='status',
        ),
    ]
